# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build

on: [push]

jobs:
  checks:
    runs-on: ubuntu-latest
    container: eclipse-temurin:17-jdk
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Run Checks
        run: ./gradlew --stacktrace -PjavafxPlatform=linux build
  run-infer:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - name : run infer action
        uses: docker://ghcr.io/martinwitt/infer-train:master
        with:
            build-command: "./gradlew --stacktrace -PjavafxPlatform=linux build"
            use-annotations: "true"